services:
  - type: web
    name: resumedia-frontend
    env: node
    plan: free
    rootDir: ResumeDia-Complete-Frontend/resumedia-frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
